// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MAntrianCounterAudio
{
    public long IdCounterAudio { get; set; }

    public string KdCounter { get; set; }

    public string Counter { get; set; }

    public bool? IsAktif { get; set; }

    public string KdLokasi { get; set; }

    public string KdLayanan { get; set; }

    public string File { get; set; }

    public string Nomor { get; set; }
}