// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MAntrianLayanan
{
    public long IdLayanan { get; set; }

    public string KdLayanan { get; set; }

    public string Layanan { get; set; }

    public bool? IsAktif { get; set; }

    public string Inisial { get; set; }

    public string KdLokasi { get; set; }
}