// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MAsal
{
    public long IdAsal { get; set; }

    public int? IdAsalGroup { get; set; }

    public string Kdasal { get; set; }

    public string NmAsal { get; set; }

    public bool IsAktif { get; set; }

    public virtual MAsalGroup IdAsalGroupNavigation { get; set; }
}