// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MCoaSubKlasifikasi
{
    public Guid IdSubKlasifikasi { get; set; }

    public decimal OldIdSubKlasifikasi { get; set; }

    public string KdSubKlasifikasi { get; set; }

    public string NmSubKlasifikasi { get; set; }

    public decimal? Urut { get; set; }

    public string Dc { get; set; }

    public bool? IsAktif { get; set; }

    public decimal? IdKlasifikasi { get; set; }

    public virtual MCoaKlasifikasi IdKlasifikasiNavigation { get; set; }

    public virtual ICollection<MCoa> MCoa { get; set; } = new List<MCoa>();
}