// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MCoa
{
    public Guid IdCoa { get; set; }

    public decimal OldIdCoa { get; set; }

    public string Kdakun { get; set; }

    public string NmAkun { get; set; }

    public string NmAkunAlias { get; set; }

    public string Dc { get; set; }

    public DateTime? TglSaldoAwal { get; set; }

    public decimal? SaldoAwal { get; set; }

    public Guid? Subklasifikasi { get; set; }

    public decimal? OldSubklasifikasi { get; set; }

    public bool? IsAktif { get; set; }

    public virtual ICollection<MDokter> MDokter { get; set; } = new List<MDokter>();

    public virtual MCoaSubKlasifikasi SubklasifikasiNavigation { get; set; }
}