// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MCountTraffic
{
    public Guid IdCountTraffic { get; set; }

    public decimal OldIdCountTraffic { get; set; }

    public DateTime? Tanggal { get; set; }

    public string Jam { get; set; }

    public string Menu { get; set; }

    public string SubMenu { get; set; }

    public string By { get; set; }
}