// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MDokter
{
    public decimal IdDokter { get; set; }

    public string KdDokter { get; set; }

    public string NmDokter { get; set; }

    public string SpesialisasiDokter { get; set; }

    public string AlamatDokter { get; set; }

    public string TelpDokter { get; set; }

    public string AlamatPraktek { get; set; }

    public string Telppraktek { get; set; }

    public bool? IsAktif { get; set; }

    public string ImgFotodokter { get; set; }

    public string KodeTarif { get; set; }

    public string KdAkun { get; set; }

    public Guid? IdCoa { get; set; }

    public string By { get; set; }

    public string IsTtd { get; set; }

    public decimal? Pin { get; set; }

    public string NoSip { get; set; }

    public virtual MCoa IdCoaNavigation { get; set; }

    public virtual ICollection<MJadwalDokter> MJadwalDokter { get; set; } = new List<MJadwalDokter>();

    public virtual ICollection<MUser> MUser { get; set; } = new List<MUser>();
}