// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MDokterHonor
{
    public decimal Id { get; set; }

    public string KdDokter { get; set; }

    public string NmDokter { get; set; }

    public decimal? Tarif { get; set; }

    public decimal? JasaMedis { get; set; }

    public decimal? JasaRs { get; set; }

    public string Ket { get; set; }
}