// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MDtd
{
    public decimal IdDtd { get; set; }

    public string KdDtd { get; set; }

    public string NmDtd { get; set; }

    public bool? IsAktif { get; set; }
}