// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MFarmakoterapi
{
    public decimal IdFarmakoterapi { get; set; }

    public string Nmfarmakoterapi { get; set; }

    public bool? IsAktif { get; set; }

    public virtual ICollection<MBarang> MBarang { get; set; } = new List<MBarang>();

    public virtual ICollection<MFarmakoterapiSub> MFarmakoterapiSub { get; set; } = new List<MFarmakoterapiSub>();
}