// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MGizi
{
    public Guid IdGizi { get; set; }

    public decimal OldIdGizi { get; set; }

    public string Kdmakanan { get; set; }

    public string Nmmakanan { get; set; }

    public string Group { get; set; }

    public string Note { get; set; }

    public string Kandungan { get; set; }

    public decimal? Energi { get; set; }

    public decimal? Protein { get; set; }

    public decimal? Lemak { get; set; }

    public decimal? Kh { get; set; }

    public decimal? Calsium { get; set; }

    public decimal? Fosfor { get; set; }

    public decimal? Fe { get; set; }

    public decimal? Vita { get; set; }

    public decimal? Vitb1 { get; set; }

    public decimal? Vitc { get; set; }

    public decimal? Air { get; set; }

    public decimal? Bdd { get; set; }

    public bool? IsAktif { get; set; }
}