// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MHargaRekanan
{
    public Guid IdHargaRekanan { get; set; }

    public decimal OldIdHargaRekanan { get; set; }

    public decimal? OldBarangId { get; set; }

    public Guid? BarangId { get; set; }

    public decimal? RekananId { get; set; }

    public decimal? Harga { get; set; }

    public DateTime? LastUpdate { get; set; }

    public string InpuBy { get; set; }

    public decimal? Margin { get; set; }

    public decimal? Diskon { get; set; }

    public decimal? Ppn { get; set; }

    public decimal? Hargajual { get; set; }

    public bool? IsAktif { get; set; }

    public virtual MBarang Barang { get; set; }

    public virtual MRekanan Rekanan { get; set; }
}