// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MHargaBarang
{
    public Guid IdHargaBeli { get; set; }

    public decimal OldIdHargaBeli { get; set; }

    public Guid? BarangId { get; set; }

    public decimal? OldBarangId { get; set; }

    public decimal? SupplierId { get; set; }

    public DateTime? LastUpdate { get; set; }

    public decimal? Harga { get; set; }

    public string InputBy { get; set; }

    public decimal? DiskonOn { get; set; }

    public decimal? DiskonOff { get; set; }

    public decimal? Ppn { get; set; }

    public bool? IsAktif { get; set; }

    public virtual MBarang Barang { get; set; }

    public virtual MSupplier Supplier { get; set; }
}