// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MKamarinap
{
    public decimal IdKamarInap { get; set; }

    public string KdTmpTidur { get; set; }

    public string Kelas { get; set; }

    public decimal? IdHargakamar { get; set; }

    public string Lantai { get; set; }

    public string Nokamar { get; set; }

    public string KodeTarif { get; set; }

    public string KodeRuangan { get; set; }

    public char Isi { get; set; }

    public int? Ix { get; set; }

    public int? Iy { get; set; }

    public decimal? IdMapid { get; set; }

    public bool? IsAktif { get; set; }

    public virtual MHargakamar IdHargakamarNavigation { get; set; }

    public virtual MMap IdMap { get; set; }

    public virtual ICollection<MKamarinapHarga> MKamarinapHarga { get; set; } = new List<MKamarinapHarga>();
}