// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MKamarinapHarga
{
    public decimal IdKamarInapHarga { get; set; }

    public string KdTmpTidur { get; set; }

    public decimal? IdKamarInap { get; set; }

    public decimal? RekananId { get; set; }

    public decimal? Harga { get; set; }

    public decimal? BeaPasien { get; set; }

    public decimal? BeaRekanan { get; set; }

    public decimal? JasaMedis { get; set; }

    public decimal? JasaRs { get; set; }

    public decimal? Bahanalkes { get; set; }

    public decimal? Diskon { get; set; }

    public decimal? Dcito { get; set; }

    public decimal? Dpenyulit { get; set; }

    public decimal? SecondTnd { get; set; }

    public decimal? Adm { get; set; }

    public DateTime? Tglawal { get; set; }

    public DateTime? Tglakhir { get; set; }

    public string By { get; set; }

    public bool? IsAktif { get; set; }

    public virtual MKamarinap IdKamarInapNavigation { get; set; }
}