// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MKodepos
{
    public int IdKodepos { get; set; }

    public string KdKodePos { get; set; }

    public string Kelurahan { get; set; }

    public string Kecamatan { get; set; }

    public string Kabupaten { get; set; }

    public string Provinsi { get; set; }

    public bool? IsAktif { get; set; }
}