// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MLaboratoriumRekanan
{
    public decimal IdLabrekanan { get; set; }

    public string KdPemeriksaanLab { get; set; }

    public decimal? IdPemeriksaanLab { get; set; }

    public decimal RekananId { get; set; }

    public bool? IsAktif { get; set; }

    public virtual MLaboratorium IdPemeriksaanLabNavigation { get; set; }

    public virtual MRekanan Rekanan { get; set; }
}