// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MLaboratoriumGroup
{
    public decimal IdGroup { get; set; }

    public string Nmgroup { get; set; }

    public bool? IsAktif { get; set; }

    public decimal? IdGrouptarif { get; set; }

    public bool? IsPk { get; set; }

    public virtual ICollection<MLaboratorium> MLaboratorium { get; set; } = new List<MLaboratorium>();
}