// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MMasterPaketH
{
    public Guid Id { get; set; }

    public decimal OldId { get; set; }

    public decimal? IdMasterPemeriksaan { get; set; }

    public string NmPemeriksaan { get; set; }

    public string KdPemeriksaan { get; set; }

    public decimal? Harga { get; set; }

    public string Penunjang { get; set; }

    public decimal? IdGroupTarif { get; set; }
}