// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MMasterTnd
{
    public double IdGroupTarif { get; set; }

    public string NmgroupTarif { get; set; }

    public string KdTarifDetail { get; set; }

    public string NmTarifDetail { get; set; }

    public string Kelas { get; set; }

    public double? Harga { get; set; }

    public double? IsAktif { get; set; }

    public double? HargaBpjs { get; set; }
}