// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MPaketRekanan
{
    public Guid IdPaketRekanan { get; set; }

    public decimal OldIdPaketRekanan { get; set; }

    public Guid IdMasterPemeriksaanPenunjang { get; set; }

    public decimal OldIdMasterPemeriksaanPenunjang { get; set; }

    public Guid RekananId { get; set; }

    public decimal OldRekananId { get; set; }

    public bool? IsAktif { get; set; }
}