// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MPaketHarga
{
    public Guid IdPaketkelas { get; set; }

    public decimal OldIdPaketkelas { get; set; }

    public Guid IdMasterPemeriksaanPenunjang { get; set; }

    public decimal OldIdMasterPemeriksaanPenunjang { get; set; }

    public Guid? IdPenunjangDetail { get; set; }

    public decimal? OldIdPenunjangDetail { get; set; }

    public Guid RekananId { get; set; }

    public decimal OldRekananid { get; set; }

    public string Kelas { get; set; }

    public decimal? Jumlah { get; set; }

    public decimal? Harga { get; set; }

    public decimal? Cito { get; set; }

    public decimal? Penyulit { get; set; }

    public decimal? SecondTnd { get; set; }

    public decimal? Adm { get; set; }

    public decimal? Diskon { get; set; }

    public decimal? Subtotal { get; set; }

    public decimal? Beapasien { get; set; }

    public decimal? Bearekanan { get; set; }

    public decimal? Jasamedis { get; set; }

    public decimal? Jasamedis2 { get; set; }

    public decimal? Jasamedis3 { get; set; }

    public decimal? Jasamedis4 { get; set; }

    public decimal? Jasamedis5 { get; set; }

    public decimal? JasaRs { get; set; }

    public decimal? BahanAlkes { get; set; }

    public DateTime? TglAwal { get; set; }

    public DateTime? TglAkhir { get; set; }

    public DateTime? LastUpdate { get; set; }

    public string By { get; set; }

    public bool? IsAktif { get; set; }
}