// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MPasien
{
    public Guid IdPasien { get; set; }

    public decimal OldIdPasien { get; set; }

    public string PasienNo { get; set; }

    public string NamaPasien { get; set; }

    public string NamaKelPasien { get; set; }

    public string Kelaminpasien { get; set; }

    public string Tmptlahirpasien { get; set; }

    public DateTime? Tgllahirpasien { get; set; }

    public string AgamaPasien { get; set; }

    public string StatusKwnpasien { get; set; }

    public string PendidikanPasien { get; set; }

    public string PekerjaanPasien { get; set; }

    public string AlamatPekerjaan { get; set; }

    public string TelpPekerjaan { get; set; }

    public string Noktpsimpasien { get; set; }

    public string JenisIdentitas { get; set; }

    public string NoPenjamin { get; set; }

    public string AlamatPasien { get; set; }

    public string KotaPasien { get; set; }

    public string TelpPasien { get; set; }

    public string HpPasien { get; set; }

    public string AlergiPasien { get; set; }

    public string CatKhusPasien { get; set; }

    public string AyahPasien { get; set; }

    public string IbuPasien { get; set; }

    public string PasanganPasien { get; set; }

    public string NamaPenanggung { get; set; }

    public string AlamatPenanggung { get; set; }

    public string TelpPenanggung { get; set; }

    public string Kodepos { get; set; }

    public string Petugas { get; set; }

    public string Rhesus { get; set; }

    public string Goldarah { get; set; }

    public DateTime? Tgldaftar { get; set; }

    public char Iscetakkartu { get; set; }

    public string Warganegara { get; set; }

    public string Jenispasien { get; set; }

    public decimal? RekananId { get; set; }

    public string By { get; set; }

    public bool? IsAktif { get; set; }

    public string Suku { get; set; }

    public string Perusahaan { get; set; }

    public string Provinsi { get; set; }

    public bool? IsBlacklist { get; set; }

    public bool? IsKunjungan { get; set; }

    public virtual MRekanan Rekanan { get; set; }
}