// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MPemeriksaanPenunjang
{
    public decimal IdMasterPemeriksaanPenunjang { get; set; }

    public string KdPemeriksaan { get; set; }

    public string NmPemeriksaan { get; set; }

    public decimal? Harga { get; set; }

    public decimal? BeaPasien { get; set; }

    public decimal? BeaRekanan { get; set; }

    public string Penunjang { get; set; }

    public Guid RekananId { get; set; }

    public decimal OldRekananId { get; set; }

    public string By { get; set; }

    public bool? IsAktif { get; set; }

    public Guid IdGroupTarif { get; set; }

    public decimal? OldIdGroupTarif { get; set; }

    public virtual ICollection<MPemeriksaanPenunjangDetail> MPemeriksaanPenunjangDetail { get; set; } = new List<MPemeriksaanPenunjangDetail>();
}