// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MRadiologiHarga
{
    public decimal IdRadHarga { get; set; }

    public string KdPemeriksaanRad { get; set; }

    public decimal? IdPemeriksaanRad { get; set; }

    public decimal RekananId { get; set; }

    public string Kelas { get; set; }

    public decimal? IdHargakamar { get; set; }

    public decimal? Harga { get; set; }

    public decimal? BeaPasien { get; set; }

    public decimal? BeaRekanan { get; set; }

    public decimal? JasaMedis { get; set; }

    public decimal? JasaRs { get; set; }

    public decimal? BahanAlkes { get; set; }

    public decimal? Diskon { get; set; }

    public decimal? Cito { get; set; }

    public decimal? Penyulit { get; set; }

    public decimal? SecondTnd { get; set; }

    public decimal? Adm { get; set; }

    public DateTime? Tglawal { get; set; }

    public DateTime? Tglakhir { get; set; }

    public string By { get; set; }

    public bool? IsAktif { get; set; }

    public DateTime? Lastupdate { get; set; }

    public virtual MHargakamar IdHargakamarNavigation { get; set; }

    public virtual MRadiologi IdPemeriksaanRadNavigation { get; set; }

    public virtual MRekanan Rekanan { get; set; }
}