// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MSettingPemeriksaan
{
    public int IdSettingPeriksaan { get; set; }

    public string NmPemeriksaan { get; set; }

    public string Group { get; set; }

    public bool? IsTampil { get; set; }
}