// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MSettingAdm
{
    public decimal IdSettingAdm { get; set; }

    public Guid RekananId { get; set; }

    public decimal? OldRekananId { get; set; }

    public string Kategori { get; set; }

    public decimal? Biaya { get; set; }

    public decimal? Percent { get; set; }
}