// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MSettingKomputerAntrian
{
    public int IdSettingKomp { get; set; }

    public string NmKomputer { get; set; }

    public string KdLokasi { get; set; }

    public string KdJenisLayanan { get; set; }

    public string KdCounter { get; set; }

    public DateTime? Tanggal { get; set; }
}