// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MSettingDaftar
{
    public int IdSettingdaftar { get; set; }

    public string NmUnitDaftar { get; set; }

    public string Koderuangan { get; set; }

    public string Tujuan { get; set; }

    public bool? IsTampil { get; set; }
}