// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MSettingBayar
{
    public int IdSettingBayar { get; set; }

    public string CaraBayar { get; set; }

    public string KdAkun { get; set; }
}