// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MSmf
{
    public int IdSmf { get; set; }

    public string Kdsmf { get; set; }

    public string Nmsmf { get; set; }

    public bool? IsAktif { get; set; }
}