// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MSupplier
{
    public decimal SupplierId { get; set; }

    public string NamaSupplier { get; set; }

    public string Alamat { get; set; }

    public string Cp { get; set; }

    public string Fax { get; set; }

    public string Kota { get; set; }

    public string Telpon { get; set; }

    public string Note { get; set; }

    public bool? IsAktif { get; set; }

    public string KdAkun { get; set; }

    public virtual ICollection<MHargaBarang> MHargaBarang { get; set; } = new List<MHargaBarang>();
}