// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MTarifnonmedisHarga
{
    public int IdNonmedishrg { get; set; }

    public string Kdtarif { get; set; }

    public decimal? IdTarifNon { get; set; }

    public decimal? Harga { get; set; }

    public decimal? Beapasien { get; set; }

    public decimal? Bearekanan { get; set; }

    public decimal? OldRekananId { get; set; }

    public Guid? RekananId { get; set; }

    public bool? IsAktif { get; set; }

    public virtual MTarifNonMedis IdTarifNonNavigation { get; set; }
}