// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MTarifnonmedisRekanan
{
    public int IdNonMedRek { get; set; }

    public string KdTarif { get; set; }

    public decimal IdTarifNon { get; set; }

    public decimal? OldIdRekanan { get; set; }

    public Guid IdRekanan { get; set; }

    public bool? IsAktif { get; set; }

    public virtual MTarifNonMedis IdTarifNonNavigation { get; set; }
}