// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MTarifRekananSub
{
    public Guid IdTarifrekanansub { get; set; }

    public decimal IdTarifRekananSub1 { get; set; }

    public decimal RekananIdHd { get; set; }

    public decimal RekananidDt { get; set; }
}