// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MTindakan
{
    public decimal IdTindakan { get; set; }

    public string KdTindakan { get; set; }

    public string NmTindakan { get; set; }

    public string NmPendek { get; set; }

    public bool? IsAktif { get; set; }
}