version: '3.4'

services:
  simplecliniq.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - DB_CONNECTION_STRING=Server=simplecliniq.czwkw6ameocg.ap-southeast-1.rds.amazonaws.com;Database=db_simple_cliniq;User Id=postgres;Password=development()qwerty34
      - ASPNETCORE_Kestrel__Certificates__Default__Password=secret
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/aspnetapp.pfx
    ports:
        - "7000:8080"
        - "8000:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro