// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MAntrianCounter
{
    public long IdCounter { get; set; }

    public string Kdcounter { get; set; }

    public string Counter { get; set; }

    public bool? IsAktif { get; set; }

    public string Kdlokasi { get; set; }

    public string Kdlayanan { get; set; }
}