// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MAsalGroup
{
    public int IdAsalGroup { get; set; }

    public string NamaGroupAsal { get; set; }

    public bool? IsAktif { get; set; }

    public virtual ICollection<MAsal> MAsal { get; set; } = new List<MAsal>();
}