// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MAturanPakai
{
    public decimal IdAturanpakai { get; set; }

    public string KdAturanPakai { get; set; }

    public string NamaAturanpakai { get; set; }

    public string KetAturanpakai { get; set; }

    public bool? IsAktif { get; set; }
}