// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MBank
{
    public Guid IdBank { get; set; }

    public decimal OldIdBank { get; set; }

    public string Kdbank { get; set; }

    public string NmBank { get; set; }

    public string Cabang { get; set; }

    public string Alamat { get; set; }

    public string Kota { get; set; }

    public string Telepon { get; set; }

    public bool IsAktif { get; set; }

    public string NomorRekening { get; set; }

    public string KdAkun { get; set; }
}