// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MBarangAturanpakai
{
    public decimal IdAturanpakai { get; set; }

    public string KdAturanPakai { get; set; }

    public string NmAturanPakai { get; set; }

    public string KetAturanPakai { get; set; }
}