// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MBarang
{
    public Guid BarangId { get; set; }

    public decimal OldBarangId { get; set; }

    public decimal? KelompokId { get; set; }

    public string Kode { get; set; }

    public string Nama { get; set; }

    public string Satuan { get; set; }

    public string Merk { get; set; }

    public string Ukuran { get; set; }

    public string Jenis { get; set; }

    public DateTime? ExpiredDate { get; set; }

    public string Etiket { get; set; }

    public decimal? Isi { get; set; }

    public string Kandungan { get; set; }

    public string Kemasan { get; set; }

    public string Pabrik { get; set; }

    public char TipeBarang { get; set; }

    public string Note { get; set; }

    public string Farmakoterapi { get; set; }

    public string SubFarmakoterapi { get; set; }

    public decimal? IdFarmakoterapi { get; set; }

    public decimal? IdSubFarmakoterapi { get; set; }

    public decimal? HargaBeli { get; set; }

    public decimal? DiskonOn { get; set; }

    public decimal? HargaJual { get; set; }

    public decimal? DiskonOff { get; set; }

    public decimal? StokMin { get; set; }

    public decimal? StokMax { get; set; }

    public decimal? StokNow { get; set; }

    public string NoBatch { get; set; }

    public byte[] Timestamp { get; set; }

    public bool? IsAktif { get; set; }

    public bool? IsFormularium { get; set; }

    public bool? EtiketQty { get; set; }

    public virtual MFarmakoterapi IdFarmakoterapiNavigation { get; set; }

    public virtual MFarmakoterapiSub IdSubFarmakoterapiNavigation { get; set; }

    public virtual MKelompokBarang Kelompok { get; set; }

    public virtual ICollection<MHargaBarang> MHargaBarang { get; set; } = new List<MHargaBarang>();

    public virtual ICollection<MHargaRekanan> MHargaRekanan { get; set; } = new List<MHargaRekanan>();
}