// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MCoaGolongan
{
    public decimal IdGolongan { get; set; }

    public string NmGolongan { get; set; }

    public bool? IsAktif { get; set; }

    public virtual ICollection<MCoaKlasifikasi> MCoaKlasifikasi { get; set; } = new List<MCoaKlasifikasi>();
}