// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MCoaKlasifikasi
{
    public decimal IdKlasifikasi { get; set; }

    public string NmKlasifikasi { get; set; }

    public decimal? Urut { get; set; }

    public bool? IsAktif { get; set; }

    public decimal? IdGolongan { get; set; }

    public virtual MCoaGolongan IdGolonganNavigation { get; set; }

    public virtual ICollection<MCoaSubKlasifikasi> MCoaSubKlasifikasi { get; set; } = new List<MCoaSubKlasifikasi>();
}