// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MDepartment
{
    public decimal IdDepartment { get; set; }

    public string NamaDepartemen { get; set; }
}