// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MDiagnosaMatrix
{
    public long IdMatrixDiagnosa { get; set; }

    public decimal IdRuangan { get; set; }

    public string KodeRuangan { get; set; }

    public decimal IdDiagnosa { get; set; }

    public string KdDiagnosa { get; set; }

    public bool? IsAktif { get; set; }
}