// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MFarmakoterapiSub
{
    public decimal IdSubFarmakoterapi { get; set; }

    public string NmSubFarmakoterapi { get; set; }

    public decimal? IdFarmakoterapi { get; set; }

    public bool? IsAktif { get; set; }

    public virtual MFarmakoterapi IdFarmakoterapiNavigation { get; set; }

    public virtual ICollection<MBarang> MBarang { get; set; } = new List<MBarang>();
}