// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MGudang
{
    public decimal IdGudangObat { get; set; }

    public string KodeInventory { get; set; }

    public string NamaGudangObat { get; set; }

    public bool? IsAktif { get; set; }

    public bool? IsRequest { get; set; }

    public bool? IsListropp { get; set; }

    public string IsTipebarang { get; set; }

    public bool? IsPaketbhp { get; set; }

    public bool? IsReturbhp { get; set; }

    public virtual ICollection<MRuang> MRuangKodeInventoryGudangObatNavigation { get; set; } = new List<MRuang>();

    public virtual ICollection<MRuang> MRuangKodeRequestGudangObatNavigation { get; set; } = new List<MRuang>();
}