// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MHargakamar
{
    public decimal IdHargakamar { get; set; }

    public string Kelas { get; set; }

    public string By { get; set; }

    public bool? IsAktif { get; set; }

    public virtual ICollection<MKamarinap> MKamarinap { get; set; } = new List<MKamarinap>();

    public virtual ICollection<MLaboratoriumHarga> MLaboratoriumHarga { get; set; } = new List<MLaboratoriumHarga>();

    public virtual ICollection<MRadiologiHarga> MRadiologiHarga { get; set; } = new List<MRadiologiHarga>();
}