// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MJadwalDokter
{
    public decimal IdJadwal { get; set; }

    public string KdDokter { get; set; }

    public decimal? IdDokter { get; set; }

    public string Hari { get; set; }

    public string JamStart { get; set; }

    public string JamFinish { get; set; }

    public string KodeRuangan { get; set; }

    public decimal? IdRuangan { get; set; }

    public string NamaKlinik { get; set; }

    public int? ServisTime { get; set; }

    public bool? IsAktif { get; set; }

    public virtual MDokter IdDokterNavigation { get; set; }

    public virtual MRuang IdRuanganNavigation { get; set; }
}