// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MKelompokBarang
{
    public decimal KelompokId { get; set; }

    public string Kode { get; set; }

    public string Nama { get; set; }

    public decimal? Margin { get; set; }

    public string Note { get; set; }

    public bool? IsAktif { get; set; }

    public decimal? IdGroupTarif { get; set; }

    public virtual ICollection<MBarang> MBarang { get; set; } = new List<MBarang>();
}