// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MLaboratoriumHarga
{
    public decimal IdLabharga { get; set; }

    public string KdPemeriksaanLab { get; set; }

    public decimal? IdPemeriksaanLab { get; set; }

    public decimal RekananId { get; set; }

    public string Kelas { get; set; }

    public decimal? IdHargakamar { get; set; }

    public decimal? Harga { get; set; }

    public decimal? Beapasien { get; set; }

    public decimal? Bearekanan { get; set; }

    public decimal? Jasamedis { get; set; }

    public decimal? Jasars { get; set; }

    public decimal? Bahanalkes { get; set; }

    public decimal? Diskon { get; set; }

    public decimal? Cito { get; set; }

    public decimal? Penyulit { get; set; }

    public decimal? SecondTnd { get; set; }

    public decimal? Adm { get; set; }

    public DateTime? Tglawal { get; set; }

    public DateTime? Tglakhir { get; set; }

    public string By { get; set; }

    public bool? IsAktif { get; set; }

    public DateTime? LastUpdate { get; set; }

    public virtual MHargakamar IdHargakamarNavigation { get; set; }

    public virtual MLaboratorium IdPemeriksaanLabNavigation { get; set; }

    public virtual MRekanan Rekanan { get; set; }
}