// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MMap
{
    public decimal IdMapid { get; set; }

    public string NmMap { get; set; }

    public string KodeRuangan { get; set; }

    public decimal? IdRuang { get; set; }

    public string Note { get; set; }

    public byte[] Image { get; set; }

    public bool? IsAktif { get; set; }

    public virtual MRuang IdRuangNavigation { get; set; }

    public virtual ICollection<MKamarinap> MKamarinap { get; set; } = new List<MKamarinap>();
}