// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MModuleDetail
{
    public int IdModuleDetail { get; set; }

    public int? IdModule { get; set; }

    public string NmModulDetail { get; set; }

    public string NmModuleDetailSub { get; set; }

    public decimal? Urut { get; set; }

    public bool? IsAktif { get; set; }

    public virtual MModule IdModuleNavigation { get; set; }
}