// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MObatUnit
{
    public decimal IdObatUnit { get; set; }

    public Guid? BarangId { get; set; }

    public decimal? OldBarangId { get; set; }

    public string KdObat { get; set; }

    public string NmObat { get; set; }

    public string KodeInventory { get; set; }

    public DateTime? ExpiredDate { get; set; }

    public decimal? StokMin { get; set; }

    public decimal? StokMax { get; set; }

    public decimal? StokNow { get; set; }

    public bool? Rod { get; set; }

    public string By { get; set; }

    public bool? IsAktif { get; set; }
}