// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MPaketMatrix
{
    public Guid IdPaketMatrix { get; set; }

    public decimal OldIdPaketmatrix { get; set; }

    public decimal IdMasterpemeriksaanpenunjang { get; set; }

    public string Koderuangan { get; set; }

    public bool? IsAktif { get; set; }
}