// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MPaketDetail
{
    public decimal IdPaketdetail { get; set; }

    public string KdPaketDetail { get; set; }

    public string NmPaketDetail { get; set; }

    public string Group { get; set; }

    public string Tipe { get; set; }

    public decimal? Harga { get; set; }

    public string Rekanan { get; set; }
}