// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MPemeriksaanPenunjangDetail
{
    public decimal IdPenunjangDetail { get; set; }

    public decimal? IdMasterPemeriksaanPenunjang { get; set; }

    public string KdPemeriksaan { get; set; }

    public string KdDetail { get; set; }

    public string NmDetail { get; set; }

    public string Group { get; set; }

    public string Tipe { get; set; }

    public decimal? Jumlah { get; set; }

    public decimal? Harga { get; set; }

    public decimal? BeaPasien { get; set; }

    public decimal? BeaRekanan { get; set; }

    public string KodeTarif { get; set; }

    public bool? IsAktif { get; set; }

    public virtual MPemeriksaanPenunjang IdMasterPemeriksaanPenunjangNavigation { get; set; }
}