// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MRadiologiGroup
{
    public decimal IdGroup { get; set; }

    public string Nmgroup { get; set; }

    public bool? IsAktif { get; set; }

    public decimal? IdGrouptarif { get; set; }

    public virtual ICollection<MRadiologi> MRadiologi { get; set; } = new List<MRadiologi>();
}