// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MRadiologi
{
    public decimal IdPemeriksaanRad { get; set; }

    public string KdPemeriksaanRad { get; set; }

    public string NmPemeriksaanRad { get; set; }

    public decimal? IdGroup { get; set; }

    public bool? IsAktif { get; set; }

    public virtual MRadiologiGroup IdGroupNavigation { get; set; }

    public virtual ICollection<MRadiologiHarga> MRadiologiHarga { get; set; } = new List<MRadiologiHarga>();

    public virtual ICollection<MRadiologiRekanan> MRadiologiRekanan { get; set; } = new List<MRadiologiRekanan>();
}