// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MRekanan
{
    public decimal IdRekanan { get; set; }

    public string NmRekanan { get; set; }

    public string Alamat { get; set; }

    public string Kota { get; set; }

    public string Telp { get; set; }

    public string Alias { get; set; }

    public bool? IsAktif { get; set; }

    public string KdAkun { get; set; }

    public bool? IsPaketBhp { get; set; }

    public bool? IsTarif { get; set; }

    public bool? IsTarifNonMed { get; set; }

    public bool IsCob { get; set; }

    public virtual ICollection<MHargaRekanan> MHargaRekanan { get; set; } = new List<MHargaRekanan>();

    public virtual ICollection<MLaboratoriumHarga> MLaboratoriumHarga { get; set; } = new List<MLaboratoriumHarga>();

    public virtual ICollection<MLaboratoriumRekanan> MLaboratoriumRekanan { get; set; } = new List<MLaboratoriumRekanan>();

    public virtual ICollection<MPasien> MPasien { get; set; } = new List<MPasien>();

    public virtual ICollection<MRadiologiHarga> MRadiologiHarga { get; set; } = new List<MRadiologiHarga>();

    public virtual ICollection<MRadiologiRekanan> MRadiologiRekanan { get; set; } = new List<MRadiologiRekanan>();
}