// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MStandartfieldGroup
{
    public decimal IdFieldgroup { get; set; }

    public string Nmfieldgroup { get; set; }

    public DateTime? Dtanggal { get; set; }

    public bool? IsAktif { get; set; }

    public string Vketerangan { get; set; }

    public virtual ICollection<MStandartfield> MStandartfield { get; set; } = new List<MStandartfield>();
}