// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MStandartfield
{
    public decimal IdField { get; set; }

    public decimal? IdFieldgroup { get; set; }

    public string KodeField { get; set; }

    public string Vdeskfield { get; set; }

    public bool? IsAktif { get; set; }

    public string Keterangan { get; set; }

    public virtual MStandartfieldGroup IdFieldgroupNavigation { get; set; }
}