// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MTarifRekanan
{
    public Guid IdTarifRekanan { get; set; }

    public decimal OldIdTarifRekanan { get; set; }

    public string KdTarifDetail { get; set; }

    public Guid RekananId { get; set; }

    public decimal OldRekananId { get; set; }

    public bool? IsAktif { get; set; }
}