// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MTarifNonMedis
{
    public decimal IdNonMedis { get; set; }

    public string KdTarif { get; set; }

    public string Nmtarif { get; set; }

    public int? IdGroupNonMedis { get; set; }

    public bool? IsAktif { get; set; }

    public virtual MTarifnonmedisGroup IdGroupNonMedisNavigation { get; set; }

    public virtual ICollection<MTarifnonmedisHarga> MTarifnonmedisHarga { get; set; } = new List<MTarifnonmedisHarga>();

    public virtual ICollection<MTarifnonmedisMatrix> MTarifnonmedisMatrix { get; set; } = new List<MTarifnonmedisMatrix>();

    public virtual ICollection<MTarifnonmedisRekanan> MTarifnonmedisRekanan { get; set; } = new List<MTarifnonmedisRekanan>();
}