// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MTarifPelayanan
{
    public int IdTariflayan { get; set; }

    public string KodeTarifLayan { get; set; }

    public string NamaTarifLayan { get; set; }

    public bool? IsAktif { get; set; }

    public virtual ICollection<MTarifDetail> MTarifDetail { get; set; } = new List<MTarifDetail>();
}