// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MTarifnonmedisMatrix
{
    public decimal IdNonMedisMatrix { get; set; }

    public string KdTarif { get; set; }

    public decimal IdNonMedis { get; set; }

    public string KodeRuangan { get; set; }

    public virtual MTarifNonMedis IdNonMedisNavigation { get; set; }
}