// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MTarifGroup
{
    public int IdGroupTarif { get; set; }

    public string NmGroupTarif { get; set; }

    public string Aliasgroup { get; set; }

    public string KdAkun { get; set; }

    public bool? IsAktif { get; set; }

    public virtual ICollection<MTarifDetail> MTarifDetail { get; set; } = new List<MTarifDetail>();
}