// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MTarifDetail
{
    public Guid IdTarifdetail { get; set; }

    public decimal OldIdTarifdetail { get; set; }

    public string KodeTarifLayan { get; set; }

    public string KdTarifDetail { get; set; }

    public string NmTarifDetail { get; set; }

    public bool? IsAktif { get; set; }

    public int? IdGroupTarif { get; set; }

    public int Kodetariflayan1 { get; set; }

    public virtual MTarifGroup IdGroupTarifNavigation { get; set; }

    public virtual MTarifPelayanan Kodetariflayan1Navigation { get; set; }
}