// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MTennant
{
    public Guid IdTenant { get; set; }

    public decimal OldIdTenant { get; set; }

    public string TenantCode { get; set; }

    public string TenantName { get; set; }

    public string TenantAddress { get; set; }

    public string Phone { get; set; }

    public string Website { get; set; }

    public string Email { get; set; }

    public string Logo { get; set; }

    public string CodeLogo { get; set; }

    public DateTime StartDateTime { get; set; }

    public DateTime ExpiredDate { get; set; }

    public string SubscriptionCode { get; set; }
}