// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MUser
{
    public Guid IdUser { get; set; }

    public decimal OldIdUser { get; set; }

    public string KodeRuangan { get; set; }

    public decimal? IdRuang { get; set; }

    public string Namalengkap { get; set; }

    public string Nmuser { get; set; }

    public string Password { get; set; }

    public string KdDokter { get; set; }

    public decimal? IdDokter { get; set; }

    public bool? IsUser { get; set; }

    public bool? IsManager { get; set; }

    public bool? IsAdmin { get; set; }

    public bool? IsMod { get; set; }

    public bool? IsDokter { get; set; }

    public bool? IsMemo { get; set; }

    public decimal? IdGroupUser { get; set; }

    public string Ttd { get; set; }

    public bool? Isaktif { get; set; }

    public string Id { get; set; }

    public bool? Transmigrated { get; set; }

    public string IdKaryawan { get; set; }

    public decimal? Pin { get; set; }

    public virtual MDokter IdDokterNavigation { get; set; }

    public virtual MUserGroup IdGroupUserNavigation { get; set; }

    public virtual MRuang IdRuangNavigation { get; set; }
}