// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MUserGroup
{
    public decimal IdGroupUser { get; set; }

    public string NmGroupUser { get; set; }

    public virtual ICollection<MUser> MUser { get; set; } = new List<MUser>();
}